name: Deploy to Cloudflare

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name for your deployment (lowercase, no spaces)'
        required: true
        default: 'rootgames'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev wrangler@4

      - name: Create D1 Database
        id: create-db
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          echo "Creating D1 database..."
          DB_INFO=$(npx wrangler d1 create ${{ github.event.inputs.project_name }})
          DB_ID=$(echo "$DB_INFO" | grep -oP 'id: \K[a-f0-9-]+')
          echo "db_id=$DB_ID" >> $GITHUB_OUTPUT
          echo "db_name=${{ github.event.inputs.project_name }}" >> $GITHUB_OUTPUT

      - name: Configure wrangler.toml
        env:
          DB_ID: ${{ steps.create-db.outputs.db_id }}
          DB_NAME: ${{ steps.create-db.outputs.db_name }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          sed -i "s/name = \"rootgames\"/name = \"$PROJECT_NAME\"/" wrangler.toml
          sed -i "s/database_name = \"rootgames\"/database_name = \"$DB_NAME\"/" wrangler.toml
          sed -i "s/database_id = \"REPLACE_WITH_YOUR_DATABASE_ID\"/database_id = \"$DB_ID\"/" wrangler.toml

      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx wrangler deploy

      - name: Initialize Database Schema
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          # Use npx to ensure wrangler v4 is used
          npx wrangler d1 execute ${{ steps.create-db.outputs.db_name }} --file=./db/schema.sql

      - name: Display Deployment URL
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_WORKERS_SUBDOMAIN: ${{ secrets.CF_WORKERS_SUBDOMAIN }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          echo "Your Root Games Tracker is now deployed!"
          echo "Visit your Worker at: https://$PROJECT_NAME.${{ secrets.CF_WORKERS_SUBDOMAIN }}.workers.dev" 